### ISSUE TITLE
A method for every single openstack command?

### ISSUE THREAD

**Issue by thutterer** [SUSE-Cloud/cct#5]
Only a few commands have been implemented so far:
https://github.com/SUSE-Cloud/cct/commit/993baf22a66d6f60eff0d4680b7f1ab53ae3ab94
https://github.com/SUSE-Cloud/cct/commit/48519caef3e4266ec7cca59cd72d6b0c4ea42c86
But we already have code duplications and differences:
https://github.com/SUSE-Cloud/cct/commit/ab689c1822abac5b48abeb5096b0b21a3e73f9be
And looking at the length of the list of [openstack commands](http://docs.openstack.org/developer/python-openstackclient/command-list.html), we should consider a more generic way to implement these helpers, e.g. the code for listing users and images is basically the same and should be reusable when I want to list tenants (projects).

**Comment by vmoravec** [comment]
In general I agree with you, I just did not want to optimize these things too early and too much as we have currently only 2 `openstackclient` commands covered.

**Comment by thutterer** [comment]
Yes, but I'd need `project` now and the necessary code for introducing `openstack project list` or `show` functionality would be only duplication.
Those to sub-commands should be inherited from some parent class, don't you think?

**Comment by vmoravec** [comment]
Or module that is included into the context. We're already including `NodeContext` into the commands classes, we might add them there (or into a new module that is included into the `NodeContext`): https://github.com/SUSE-Cloud/cct/blob/master/lib/cct/commands/openstack.rb#L22 

Or would you rather convert that module into a class and inherit from it for every `openstackclient` command (I mean here this class: https://github.com/SUSE-Cloud/cct/blob/master/lib/cct/commands/openstack/user.rb#L4) ?

**Comment by thutterer** [comment]
Puh, that's a design questions on which I don't have any particular opinion.

**Comment by vmoravec** [comment]
This is the proposal to simpify the commands' implementation: [Add openstack client refactored api](https://github.com/SUSE-Cloud/cct/pull/6)

**Comment by thutterer** [comment]
Thanks for improving this right away!

Edit: I just saw the PR isn't merged yet but I keep this issue closed as this will eventually go into master.
